// ============================================================
// Mock data for development (replace with Supabase queries)
// ============================================================
import type { Workspace, Task, Agent, ActivityLogEntry, Alert, DailySummary } from './types'

export const mockWorkspaces: Workspace[] = [
  {
    id: '1',
    name: 'Ritmo Fit',
    slug: 'ritmo-fit',
    description: 'Academia e lifestyle fitness',
    logo_url: null,
    color: '#ff6b6b',
    niche: 'Fitness',
    goals: {},
    onboarding_data: {},
    is_prospect: false,
    prospect_score: null,
    status: 'active',
    owner_id: null,
    whatsapp_number: '+5511999990001',
    whatsapp_active: true,
    instagram_handle: 'ritmofit',
    twitter_handle: null,
    website_url: null,
    industry: 'Fitness',
    monthly_budget: 5000,
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: '2',
    name: 'Gourmet Casa',
    slug: 'gourmet-casa',
    description: 'Restaurante e delivery premium',
    logo_url: null,
    color: '#f59e0b',
    niche: 'Food & Beverage',
    goals: {},
    onboarding_data: {},
    is_prospect: false,
    prospect_score: null,
    status: 'active',
    owner_id: null,
    whatsapp_number: '+5511999990002',
    whatsapp_active: true,
    instagram_handle: 'gourmetcasa',
    twitter_handle: null,
    website_url: null,
    industry: 'Food & Beverage',
    monthly_budget: 3500,
    created_at: '2025-02-10T00:00:00Z',
    updated_at: '2026-03-20T09:00:00Z',
  },
  {
    id: '3',
    name: 'TechNova',
    slug: 'technova',
    description: 'SaaS B2B de gestão',
    logo_url: null,
    color: '#9b59ff',
    niche: 'SaaS',
    goals: {},
    onboarding_data: {},
    is_prospect: false,
    prospect_score: null,
    status: 'active',
    owner_id: null,
    whatsapp_number: null,
    whatsapp_active: false,
    instagram_handle: 'technovaapp',
    twitter_handle: 'technova',
    website_url: 'https://technova.app',
    industry: 'SaaS',
    monthly_budget: 8000,
    created_at: '2025-03-01T00:00:00Z',
    updated_at: '2026-03-19T18:00:00Z',
  },
  {
    id: '4',
    name: 'Beleza & Arte',
    slug: 'beleza-arte',
    description: 'Salão de beleza premium',
    logo_url: null,
    color: '#ff4dca',
    niche: 'Beauty',
    goals: {},
    onboarding_data: {},
    is_prospect: false,
    prospect_score: null,
    status: 'active',
    owner_id: null,
    whatsapp_number: '+5511999990004',
    whatsapp_active: true,
    instagram_handle: 'belezaearte',
    twitter_handle: null,
    website_url: null,
    industry: 'Beauty',
    monthly_budget: 2500,
    created_at: '2025-04-05T00:00:00Z',
    updated_at: '2026-03-20T08:00:00Z',
  },
]

export const mockAlerts: Alert[] = [
  {
    id: '1',
    workspace: 'Ritmo Fit',
    workspaceColor: '#ff6b6b',
    message: 'Taxa de engajamento caiu 23% nos últimos 3 dias — verificar conteúdo publicado',
    severity: 'critical',
    timestamp: '2026-03-21T08:30:00Z',
  },
  {
    id: '2',
    workspace: 'TechNova',
    workspaceColor: '#9b59ff',
    message: 'Relatório semanal pendente de aprovação antes das 18h',
    severity: 'warning',
    timestamp: '2026-03-21T09:00:00Z',
  },
  {
    id: '3',
    workspace: 'Gourmet Casa',
    workspaceColor: '#f59e0b',
    message: 'Agente de conteúdo parou de responder — reiniciar necessário',
    severity: 'critical',
    timestamp: '2026-03-21T07:45:00Z',
  },
]

export const mockDailySummary: DailySummary = {
  id: '1',
  workspace_id: null,
  date: '2026-03-21',
  summary: 'Dia intenso: 4 clientes ativos com 12 tasks abertas. Destaque para o crescimento de 18% em engajamento da Beleza & Arte. TechNova bateu meta de leads da semana com 2 dias de antecedência.',
  highlights: [
    'Beleza & Arte: +18% engajamento no Reels de ontem',
    'TechNova: 47 novos leads qualificados na semana',
    'Gourmet Casa: cardápio de Páscoa publicado com sucesso',
  ],
  alerts: ['Ritmo Fit: queda de engajamento', 'Agente Gourmet Casa offline'],
  metrics_delta: {},
  generated_at: '2026-03-21T06:00:00Z',
  created_at: '2026-03-21T06:00:00Z',
}

export const mockTasks: Task[] = [
  {
    id: 't1',
    workspace_id: '1',
    agent_id: null,
    assigned_to: null,
    title: 'Criar 5 Reels para campanha de Páscoa',
    description: null,
    status: 'todo',
    priority: 'high',
    due_date: '2026-03-28T00:00:00Z',
    tags: ['conteúdo', 'páscoa'],
    attachments: [],
    metadata: {},
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 't2',
    workspace_id: '3',
    agent_id: null,
    assigned_to: null,
    title: 'Analisar concorrentes SaaS Q1',
    description: null,
    status: 'todo',
    priority: 'medium',
    due_date: '2026-03-25T00:00:00Z',
    tags: ['análise', 'competidores'],
    attachments: [],
    metadata: {},
    created_at: '2026-03-19T15:00:00Z',
    updated_at: '2026-03-19T15:00:00Z',
  },
  {
    id: 't3',
    workspace_id: '2',
    agent_id: null,
    assigned_to: null,
    title: 'Publicar cardápio especial Páscoa',
    description: null,
    status: 'doing',
    priority: 'urgent',
    due_date: '2026-03-21T00:00:00Z',
    tags: ['conteúdo', 'urgente'],
    attachments: [],
    metadata: {},
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-03-21T07:00:00Z',
  },
  {
    id: 't4',
    workspace_id: '3',
    agent_id: null,
    assigned_to: null,
    title: 'Configurar automação de e-mail nurture',
    description: null,
    status: 'doing',
    priority: 'high',
    due_date: '2026-03-22T00:00:00Z',
    tags: ['automação', 'email'],
    attachments: [],
    metadata: {},
    created_at: '2026-03-18T14:00:00Z',
    updated_at: '2026-03-20T16:00:00Z',
  },
  {
    id: 't5',
    workspace_id: '4',
    agent_id: null,
    assigned_to: null,
    title: 'Relatório de resultado fevereiro',
    description: null,
    status: 'done',
    priority: 'medium',
    due_date: '2026-03-15T00:00:00Z',
    tags: ['relatório'],
    attachments: [],
    metadata: {},
    created_at: '2026-03-10T10:00:00Z',
    updated_at: '2026-03-15T17:00:00Z',
  },
  {
    id: 't6',
    workspace_id: '1',
    agent_id: null,
    assigned_to: null,
    title: 'Briefing para campanha verão',
    description: null,
    status: 'done',
    priority: 'low',
    due_date: '2026-03-18T00:00:00Z',
    tags: ['planejamento'],
    attachments: [],
    metadata: {},
    created_at: '2026-03-12T11:00:00Z',
    updated_at: '2026-03-18T10:00:00Z',
  },
]

export const mockAgents: Agent[] = [
  {
    id: 'a1', workspace_id: '1', name: 'Conteúdo Ritmo', slug: 'conteudo-ritmo',
    description: null, role: 'content', type: 'content', status: 'running',
    system_prompt: null, model: 'claude-sonnet-4-6', temperature: 0.7,
    max_tokens: 4096, tools_enabled: ['search', 'image'], last_active_at: '2026-03-21T09:30:00Z',
    is_gerentao: false, is_active: true, avatar_config: {},
    error_message: null, metadata: {}, created_at: '2025-01-15T00:00:00Z', updated_at: '2026-03-21T09:30:00Z',
  },
  {
    id: 'a2', workspace_id: '2', name: 'Chef Social', slug: 'chef-social',
    description: null, role: 'content', type: 'content', status: 'error',
    system_prompt: null, model: 'claude-sonnet-4-6', temperature: 0.8,
    max_tokens: 4096, tools_enabled: ['search'], last_active_at: '2026-03-21T07:40:00Z',
    is_gerentao: false, is_active: true, avatar_config: {},
    error_message: 'Conexão perdida com API de imagens', metadata: {}, created_at: '2025-02-10T00:00:00Z', updated_at: '2026-03-21T07:40:00Z',
  },
  {
    id: 'a3', workspace_id: '3', name: 'Growth TechNova', slug: 'growth-technova',
    description: null, role: 'analytics', type: 'analytics', status: 'running',
    system_prompt: null, model: 'claude-opus-4-6', temperature: 0.5,
    max_tokens: 8192, tools_enabled: ['search', 'code', 'browser'], last_active_at: '2026-03-21T09:45:00Z',
    is_gerentao: false, is_active: true, avatar_config: {},
    error_message: null, metadata: {}, created_at: '2025-03-01T00:00:00Z', updated_at: '2026-03-21T09:45:00Z',
  },
  {
    id: 'a4', workspace_id: '4', name: 'Beleza Trends', slug: 'beleza-trends',
    description: null, role: 'social', type: 'social', status: 'idle',
    system_prompt: null, model: 'claude-sonnet-4-6', temperature: 0.9,
    max_tokens: 4096, tools_enabled: ['search', 'image'], last_active_at: '2026-03-21T08:00:00Z',
    is_gerentao: false, is_active: true, avatar_config: {},
    error_message: null, metadata: {}, created_at: '2025-04-05T00:00:00Z', updated_at: '2026-03-21T08:00:00Z',
  },
]

export const mockActivity: ActivityLogEntry[] = [
  {
    id: 'l1', workspace_id: '3', agent_id: 'a3', user_id: null,
    action: 'task_completed', entity_type: 'task', entity_id: 't6',
    description: 'Growth TechNova finalizou análise de 47 leads qualificados',
    metadata: {}, created_at: '2026-03-21T09:45:00Z',
  },
  {
    id: 'l2', workspace_id: '4', agent_id: 'a4', user_id: null,
    action: 'content_published', entity_type: 'task', entity_id: null,
    description: 'Beleza & Arte: Reels "Tendências Outono" publicado no Instagram',
    metadata: {}, created_at: '2026-03-21T09:10:00Z',
  },
  {
    id: 'l3', workspace_id: '2', agent_id: 'a2', user_id: null,
    action: 'agent_error', entity_type: 'agent', entity_id: 'a2',
    description: 'Chef Social entrou em estado de erro — API de imagens indisponível',
    metadata: {}, created_at: '2026-03-21T07:40:00Z',
  },
  {
    id: 'l4', workspace_id: '1', agent_id: 'a1', user_id: null,
    action: 'task_started', entity_type: 'task', entity_id: 't3',
    description: 'Conteúdo Ritmo iniciou criação de Reels para campanha de Páscoa',
    metadata: {}, created_at: '2026-03-21T07:00:00Z',
  },
  {
    id: 'l5', workspace_id: null, agent_id: null, user_id: 'user-1',
    action: 'report_generated', entity_type: null, entity_id: null,
    description: 'Relatório semanal consolidado gerado para todos os clientes',
    metadata: {}, created_at: '2026-03-20T18:00:00Z',
  },
  {
    id: 'l6', workspace_id: '3', agent_id: 'a3', user_id: null,
    action: 'message_sent', entity_type: 'conversation', entity_id: null,
    description: 'Growth TechNova respondeu 12 leads via chat automatizado',
    metadata: {}, created_at: '2026-03-20T16:30:00Z',
  },
]
